<?php
namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Request;

class Index extends Controller
{
    public function _initialize()
    {
        //header('Access-Control-Allow-Origin: http://test.six_page.com');
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * @desc 接口测试
     * @param Request $request
     * @return \think\response\Json
     */
    public function queue(Request $request)
    {

        //链接redis
        $redis = new \Redis();
        $redis->connect('127.0.0.1', 6379);

        $arr = [];

        for($i=0;$i<10000;$i++){
            $num = rand(1,10000);

            $arr[] = $num;
        }

        //生产者数据
        $arr_chunk = array_chunk($arr, 200);

        foreach ($arr_chunk as $key => $value) {
            $redis->lpush('sms_phones',json_encode($value));
        }
    }

    public function consumer(Request $request)
    {
        //链接redis
        $redis = new \Redis();
        $redis->connect('127.0.0.1', 6379);

        while($redis->llen('sms_phones')>0 ){
            $phones = $redis->rpop('sms_phones');

            echo "已发送手机号".$phones;
        }
    }
}
